<template>
  <svg
    xmlns="http://www.w3.org/2000/svg"
    xmlns:xlink="http://www.w3.org/1999/xlink"
    viewBox="0 0 100 100"
    preserveAspectRatio="xMidYMid"
    width="115"
    height="115"
    style="
      shape-rendering: auto;
      display: block;
      background: rgb(255, 255, 255);
    "
  >
    <g>
      <rect x="17.5" y="30" width="15" height="40" fill="#0b1e43">
        <animate
          attributeName="y"
          repeatCount="indefinite"
          dur="1.3333333333333333s"
          calcMode="spline"
          keyTimes="0;0.5;1"
          values="18;30;30"
          keySplines="0 0.5 0.5 1;0 0.5 0.5 1"
          begin="-0.26666666666666666s"
        />
        <animate
          attributeName="height"
          repeatCount="indefinite"
          dur="1.3333333333333333s"
          calcMode="spline"
          keyTimes="0;0.5;1"
          values="64;40;40"
          keySplines="0 0.5 0.5 1;0 0.5 0.5 1"
          begin="-0.26666666666666666s"
        />
      </rect>
      <rect x="42.5" y="30" width="15" height="40" fill="#e0e0e0">
        <animate
          attributeName="y"
          repeatCount="indefinite"
          dur="1.3333333333333333s"
          calcMode="spline"
          keyTimes="0;0.5;1"
          values="20.999999999999996;30;30"
          keySplines="0 0.5 0.5 1;0 0.5 0.5 1"
          begin="-0.13333333333333333s"
        />
        <animate
          attributeName="height"
          repeatCount="indefinite"
          dur="1.3333333333333333s"
          calcMode="spline"
          keyTimes="0;0.5;1"
          values="58.00000000000001;40;40"
          keySplines="0 0.5 0.5 1;0 0.5 0.5 1"
          begin="-0.13333333333333333s"
        />
      </rect>
      <rect x="67.5" y="30" width="15" height="40" fill="#ff8c00">
        <animate
          attributeName="y"
          repeatCount="indefinite"
          dur="1.3333333333333333s"
          calcMode="spline"
          keyTimes="0;0.5;1"
          values="20.999999999999996;30;30"
          keySplines="0 0.5 0.5 1;0 0.5 0.5 1"
        />
        <animate
          attributeName="height"
          repeatCount="indefinite"
          dur="1.3333333333333333s"
          calcMode="spline"
          keyTimes="0;0.5;1"
          values="58.00000000000001;40;40"
          keySplines="0 0.5 0.5 1;0 0.5 0.5 1"
        />
      </rect>
      <g />
    </g>
    <!-- [ldio] generated by https://loading.io -->
  </svg>
</template>
